### ISSUE TITLE
Cache Page Plugin

### ISSUE THREAD

**Issue by OC2PS** [irkanu/simple-facebook-page-widget#9]
https://wordpress.org/plugins/facebook-fan-box-cache/ was a super plugin that managed to cache the Likebox. Can you learn from that to cache Page Plugin? Would be invaluable.

**Comment by irkanu** [comment]
Good suggestion. I've been thinking about this myself and haven't quiet come to the best solution. I've read over the code in the plugin you linked and it looks insecure. I also noticed it hasn't been updated in over 2 years - that's concerning. I'd love to look at a more recent example using Facebook's latest API.

If you have anymore recent resources for me to look at, then I'd love to see them and help get a cached version created. Otherwise, if you'd like to write it, then I'd be happy to review your pull request. :)

**Comment by irkanu** [comment]
I've attempted to store the widget output as a transient; however, Facebook does not allow the iframe to be loaded without reloading the data. This means the Page Plugin developed by Facebook itself naturally doesn't allow caching. If someone is able to find a way around this, then I'm happy to see their code, but for now I'm going to close this. :+1:
